spring:
  profiles:
    include: secret

  application:
    name: pairding

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: postgres.omcufpoytvhaljpmsrlk

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database : postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties :
      hibernate :
        format_sql : true
        show_sql : true

  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liwG1ZHqyG6uijGr
            client-secret: 4e9d29b8e33e9e4f40f04fbd7123d1666ea3930f
            scope:
              - read:user
              - user:email
              - repo
            # redirect-uri: "{baseUrl}/login/oauth2/code/github"
            #redirect-uri: "https://turbo-telegram-9gp454rv6w5hp654-8080.app.github.dev/login/oauth2/code/github"
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/github"
            client-name: GitHub
logging:
  level:
    root: info
    com.pairding: debug

cors:
  allow-credentials: true
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type,Origin"

jwt:
  secret: "VlwEyVlPKl54t484gbR2e7dNA7N6bH7v55jB7v55jB="

scm:
  webhook:
    callback-url: https://spicy-glasses-marry.loca.lt/api/webhook/scm